# LEC 13 PYTHON 12 NumPy Examples

## NumPy
## https://docs.scipy.org/doc/numpy/reference/ufuncs.html

In [2]:
# ИМПОРТ МОДУЛЯ
import numpy as np

####  **Создание массивов numpy**. Из других объектов Python 

####  **Создаем Pyton List  и массив numpy**  **Тип разный !!!!**

In [3]:
x = [1,2,3,4]        # это список Python
y = np.array([1,2,3,4]) # это массив numpy

In [4]:
print (type(x), x)
print (type(y), y)

<class 'list'> [1, 2, 3, 4]
<class 'numpy.ndarray'> [1 2 3 4]


####  **Создаем  массив numpy**

In [5]:
z = np.array([[1,2.0],[0,0],(1+1j,3.)]) # смесь списков и кортежей
print(type(z))  # !!! МАССИВ 2 х 2  все элементы комплексные числа
print(z)

<class 'numpy.ndarray'>
[[1.+0.j 2.+0.j]
 [0.+0.j 0.+0.j]
 [1.+1.j 3.+0.j]]


####  **Создание массивов numpy**. Встроенные функции

In [6]:
arr_int_0 = np.zeros((2,3), np.int8)  # МАСИВ НУЛЕЙ  2 Х 3 (ЦЕЛЫЕ 1 БАЙТ)
print (arr_int_0)

[[0 0 0]
 [0 0 0]]


In [7]:
arr_flt_0 = np.zeros((2,3), np.float32) # МАСИВ НУЛЕЙ  2 Х 3 (32-РАЗРЯДА, ПЛАВАЮЩИЕ)
print (arr_flt_0)

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
arr_compl = np.full((2,3), 1.0 + .5j, np.complex64) # МАСИВ 2 Х 3 ЗАДАННЫХ КОМПЛЕКСНЫХ
print (arr_compl)

[[1.+0.5j 1.+0.5j 1.+0.5j]
 [1.+0.5j 1.+0.5j 1.+0.5j]]


In [9]:
arr_exmpl = np.arange(1,3,0.25, dtype = np.float64) # ЗАПОЛНЕНИЕ МАССИВА ОТ ДО С ШАГОМ
print (arr_exmpl)

[1.   1.25 1.5  1.75 2.   2.25 2.5  2.75]


In [10]:
arr_exmpl_ = np.linspace(1.0, 4.0 , 6) # РАВНОМЕРНОЕ ЗАПОЛНЕНИЕ МАССИВА 
print (arr_exmpl_)

[1.  1.6 2.2 2.8 3.4 4. ]


In [11]:
arr_exampl = np.indices((2,3)) # СОЗДАНИЕ ИДЕКСОВ РЕГУЛЯРНЫХ СЕТОК
print (arr_exampl)

[[[0 0 0]
  [1 1 1]]

 [[0 1 2]
  [0 1 2]]]


####  **Срезы работают. Вывод разный**

In [12]:
print (x[1:3])
print (y[1:3])

[2, 3]
[2 3]


####  ИНДКСАЦИЯ ! МАССИВ ИНДЕКСОВ !! ЛОГИЧЕСКАЯ ИНДЕКСАЦИЯ

In [13]:
 print (x[[0, 2]])  #  НЕ РАБОТАЕТ

TypeError: list indices must be integers or slices, not list

In [14]:
print (y[[0, 2]])   #  РАБОТАЕТ

[1 3]


In [15]:
print ( y>2)   
print ( y[y>2])   #  РАБОТАЕТ ЛОГИЧЕСКАЯ ИНДЕКСАЦИЯ

[False False  True  True]
[3 4]


####  **МАТЕМАТИЧЕСКИЕ ОПЕРАЦИИ  (+, -, *, /, sign, abs, ...)**

In [16]:
x1 = np.arange(-2.0, 2.1, 0.25)
print (x1)

[-2.   -1.75 -1.5  -1.25 -1.   -0.75 -0.5  -0.25  0.    0.25  0.5   0.75
  1.    1.25  1.5   1.75  2.  ]


In [17]:
print (np.negative(x1)) # ОТРИЦАНИЕ
print (np.positive(x1))

[ 2.    1.75  1.5   1.25  1.    0.75  0.5   0.25 -0.   -0.25 -0.5  -0.75
 -1.   -1.25 -1.5  -1.75 -2.  ]
[-2.   -1.75 -1.5  -1.25 -1.   -0.75 -0.5  -0.25  0.    0.25  0.5   0.75
  1.    1.25  1.5   1.75  2.  ]


In [18]:
x3 = np.sign(x1)  # ЗНАК
print (x3)

[-1. -1. -1. -1. -1. -1. -1. -1.  0.  1.  1.  1.  1.  1.  1.  1.  1.]


In [19]:
x2 = np.negative(x1) 
print (x2)

[ 2.    1.75  1.5   1.25  1.    0.75  0.5   0.25 -0.   -0.25 -0.5  -0.75
 -1.   -1.25 -1.5  -1.75 -2.  ]


In [20]:
print (x1+x2)   # СЛОЖЕНИЕ

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [21]:
print (x2-x1)  # ВЫЧИТАНИЕ

[ 4.   3.5  3.   2.5  2.   1.5  1.   0.5 -0.  -0.5 -1.  -1.5 -2.  -2.5
 -3.  -3.5 -4. ]


In [22]:
print (x1*x3) # УМНОЖЕНИЕ

[2.   1.75 1.5  1.25 1.   0.75 0.5  0.25 0.   0.25 0.5  0.75 1.   1.25
 1.5  1.75 2.  ]


In [23]:
print (x1 / x2) # ДЕЛЕНИЕ !! НА СКАЛЯР
print (x1 / 5) # ДЕЛЕНИЕ !! НА СКАЛЯР

[-1. -1. -1. -1. -1. -1. -1. -1. nan -1. -1. -1. -1. -1. -1. -1. -1.]
[-0.4  -0.35 -0.3  -0.25 -0.2  -0.15 -0.1  -0.05  0.    0.05  0.1   0.15
  0.2   0.25  0.3   0.35  0.4 ]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [26]:
for i  in range(len(x1)) :
    print (i, x1[i], (x1**x3)[i])    

0 -2.0 -0.5
1 -1.75 -0.5714285714285714
2 -1.5 -0.6666666666666666
3 -1.25 -0.8
4 -1.0 -1.0
5 -0.75 -1.3333333333333333
6 -0.5 -2.0
7 -0.25 -4.0
8 0.0 1.0
9 0.25 0.25
10 0.5 0.5
11 0.75 0.75
12 1.0 1.0
13 1.25 1.25
14 1.5 1.5
15 1.75 1.75
16 2.0 2.0


 #### ТРИГОНОМЕТРИЧЕСКИЕ ФУНКЦИИ  (sin, cos, ... , arcsin, arccos, ...)

In [27]:
angle = np.arange (-180, 181, 10)
rat  =  np.pi / 180.0
for i  in range(len(angle)) :
    print (i, angle[i], (np.sin(rat*angle[i])))   


0 -180 -1.2246467991473532e-16
1 -170 -0.17364817766693028
2 -160 -0.3420201433256689
3 -150 -0.49999999999999994
4 -140 -0.6427876096865395
5 -130 -0.766044443118978
6 -120 -0.8660254037844387
7 -110 -0.9396926207859084
8 -100 -0.984807753012208
9 -90 -1.0
10 -80 -0.984807753012208
11 -70 -0.9396926207859083
12 -60 -0.8660254037844386
13 -50 -0.766044443118978
14 -40 -0.6427876096865393
15 -30 -0.49999999999999994
16 -20 -0.3420201433256687
17 -10 -0.17364817766693033
18 0 0.0
19 10 0.17364817766693033
20 20 0.3420201433256687
21 30 0.49999999999999994
22 40 0.6427876096865393
23 50 0.766044443118978
24 60 0.8660254037844386
25 70 0.9396926207859083
26 80 0.984807753012208
27 90 1.0
28 100 0.984807753012208
29 110 0.9396926207859084
30 120 0.8660254037844387
31 130 0.766044443118978
32 140 0.6427876096865395
33 150 0.49999999999999994
34 160 0.3420201433256689
35 170 0.17364817766693028
36 180 1.2246467991473532e-16


### CРАВНЕНИЯ (greater, greater_equal, less, less_equal, equal, not_equal)

In [28]:
ar_less = x1 < x2
print(ar_less)

[ True  True  True  True  True  True  True  True False False False False
 False False False False False]


In [29]:
ar_max = np.fmax(x1,x2) # ПОЭЛЕМЕНТНО
print(ar_max)

[2.   1.75 1.5  1.25 1.   0.75 0.5  0.25 0.   0.25 0.5  0.75 1.   1.25
 1.5  1.75 2.  ]


In [30]:
print(np.minimum(x1,x3))
print(np.maximum(x1,x3))

[-2.   -1.75 -1.5  -1.25 -1.   -1.   -1.   -1.    0.    0.25  0.5   0.75
  1.    1.    1.    1.    1.  ]
[-1.   -1.   -1.   -1.   -1.   -0.75 -0.5  -0.25  0.    1.    1.    1.
  1.    1.25  1.5   1.75  2.  ]


### ЛОГИКА (and, or, not ....)

In [31]:
print(np.logical_and(x1,ar_less))

[ True  True  True  True  True  True  True  True False False False False
 False False False False False]


### АГРЕГАТОРЫ (min, max, ....

In [32]:
print(np.min(x1))
print(np.max(x1))

-2.0
2.0


### ГЕНЕРАТОР СЛУЧАЙНЫХ ЧИСЕЛ

In [33]:
from numpy.random import Generator, PCG64  # PCG64  - генератор случайных бит (один из возможных)
rg = Generator(PCG64())
rg.standard_normal()    # СЛУЧАЙНОЕ ЧИСЛО

-1.3108614284967022

In [34]:
rg.standard_normal(5)    # ОДНОМЕРНЫЙ МАССИВ СЛУЧАЙНЫХ ЧИСЕЛ

array([ 1.58766736, -0.90169807, -1.17116407, -0.93634297, -1.32866151])

In [35]:
rg.standard_normal((2, 3)) # МАТРИЦА  СЛУЧАЙНЫХ ЧИСЕЛ

array([[-0.14364551, -0.83517826,  0.43594819],
       [-1.21910543, -1.91760658,  0.88747909]])

In [36]:
rg.random()

0.7215519976395426

In [37]:
rg.random((5,))

array([0.03380221, 0.02907069, 0.11911143, 0.51312337, 0.83364091])

In [38]:
rg.integers(-10,10,10,np.int64,False)

array([  0,   7,  -8,   1,   6,  -1,   9,   2,   9, -10], dtype=int64)

In [39]:
rg.bytes(5)

b'\x7f?\x87Q{'

In [40]:
mu, sigma = 0, 0.1       # среднее и отклонение 
s = rg.normal(mu, sigma, 10)
print (s)

[ 0.03952713  0.00598738 -0.10236693  0.07972858  0.01144096  0.2060646
  0.08282963  0.03001647  0.08462616  0.00477409]


### СОРТИРОВКИ и др

In [41]:
rand_int = rg.integers(-20,20,10,np.int64,False)
print (rand_int)

[-18  -9   8 -13  13   9   5  -9  -8  -4]


In [42]:
print(np.sort(rand_int))

[-18 -13  -9  -9  -8  -4   5   8   9  13]


In [43]:
print(np.argsort(rand_int))

[0 3 1 7 8 9 6 2 5 4]


In [44]:
print(np.argmax(rand_int))

4


In [45]:
print(np.argmin(rand_int))

0


In [46]:
rand_int_ = rg.integers(-20,20,10,np.int64,False)
print (rand_int_)

[  2   3 -16 -12   2  -2  10  11  10 -10]


In [47]:
print (np.where(rand_int > rand_int_, rand_int, 'no'))

['no' 'no' '8' 'no' '13' '9' 'no' 'no' 'no' '-4']


### ЛИНЕЙНАЯ АЛГЕБРА

In [80]:
vect_1 = rg.integers(-10,10,10,np.int64,False)  # СОЗДАЕМ 2 ВЕКТОРА 10 компонент
vect_2 = rg.integers(-10,10,10,np.int64,False)
print (vect_1)
print (vect_2)

[ -4  -4   1  -5   5  -4  -5 -10  -3  -3]
[  1   7  -1  -8   7  -8   0 -10   0  -1]


In [81]:
vect_norm = np.linalg.norm(vect_1)  # ЭВКЛИДОВА НОРМА ВЕКТОРА
print(vect_norm)

15.556349186104045


In [82]:
scal_mult = np.dot(vect_1,vect_2)  # СКАЛЯРОНОЕ ПРОИЗВЕДЕНИЕ ВЕКТОРОВ
print(scal_mult)

177


In [83]:
# СОЗДАЕМ СЛУЧАЙНУЮ МАТРИЦУ А (10 Х 10)
matr_A = rg.random(100,np.float32) * rg.integers(-10,10,100,np.int64,False)
print (np.shape(matr_A))
matr_A = np.reshape(matr_A , (10, 10))
print (np.shape(matr_A))
# print (matr_A)

(100,)
(10, 10)


In [84]:
# СОЗДАЕМ СЛУЧАЙНЫЙ ВЕКТОР В (10)
vect_B = rg.random(10,np.float32) * rg.integers(-15,15,10,np.int64,False)
# print (vect_B)

In [87]:
# НАХОДИМ ОБРАТНУЮ МАТРИЦУ
matr_invers = np.linalg.matrix_power(matr_A, -1)  # ОБРАТНАЯ МАТРИЦА
print (matr_invers)

[[-0.00910359 -0.08374228 -0.00075285  0.09169143  0.01110539 -0.03635008
   0.14464799  0.11735614 -0.19577584 -0.15294098]
 [-0.09580212 -0.02451542  0.06719234 -0.04411631 -0.00681941  0.01201789
  -0.17666248  0.0375137  -0.02629667  0.1478195 ]
 [ 0.02792142 -0.02688606 -0.04709989  0.01545198 -0.01850575 -0.1878339
  -0.04838731  0.03266485  0.09980717  0.13190529]
 [-0.05644001 -0.00918658 -0.04713711 -0.01091719  0.01454059  0.27727466
   0.12831036  0.05758931 -0.19931842 -0.24814417]
 [-0.0303655  -0.06081888 -0.01005589 -0.00912723 -0.02603199 -0.1630082
   0.00146371  0.03512853  0.06500607 -0.06615075]
 [ 0.07088985  0.01942482 -0.00405942 -0.00687119  0.05573313  0.03594292
   0.00648227 -0.0205618  -0.02872234 -0.07265281]
 [-0.04937935  0.04881218 -0.05839582 -0.06144377  0.02179645  0.01241261
   0.05996257 -0.00709391 -0.11178371 -0.0705224 ]
 [-0.04569179 -0.05898042 -0.0341035  -0.12601969 -0.05246547 -0.0227545
   0.03758657  0.01865714 -0.04911423 -0.02225156]
 [ 

In [95]:
# НАХОДИМ РЕШЕНИЕ КАК ПРОИЗВЕДЕНИЕОБРАТНОЙ МАТРИЦЫ НА ВЕКТОР
vect_X = np.matmul(matr_invers, vect_B)
print (vect_X)

[ 3.26793582  0.59227898 -1.2440549   2.63394482 -0.99000028  0.61094416
  1.24593864  0.50521779 -6.07221945 -4.69610157]


In [93]:
# НАХОДИМ РЕШЕНИЕ СИСТЕМЫ АЛГЕБРАИЧЕСКИХ УРАВНЕНИЙ "В ЛОБ"
vect_X_ = np.linalg.solve(matr_A, vect_B)

In [94]:
print (vect_X_)

[ 3.26793582  0.59227898 -1.2440549   2.63394482 -0.99000028  0.61094416
  1.24593864  0.50521779 -6.07221945 -4.69610157]
